### PR TITLE
perf(app): Upgrade Electron to v3 and remove Node in renderer

### PR DESCRIPTION
**Pull request by mcous**
## overview

This PR is a performance/security update to:

- Upgrade Electron to 3.0.2 for various performance and security updates since 1.8.x
- Disable Node integration in the renderer process for security

## changelog

- Upgrade Electron to `v3.0.2`
    - Node `10.2.0`
    - Chromium `66.0.3359.181`
- Disable Node integration in the renderer process
    - Our renderer process still needs access to Node stuff (the `electron` module) in the app's shell client (how the app talks to app-shell) at `app/src/shell/index.js`
    - Electron allows a `preload` script to run and attach stuff to `window` before the UI is loaded for exactly the purpose of handing a safe subset of Node to the renderer
    - This is how we now access any necessary Node stuff in the renderer process

## review requests

**Important to note**: There are breaking changes since our last Electron version upgrade, so after you run this build of the app on Electron 3, you may find that older versions of the app now crash. If you need to go back to an ealier version of the app, you may need to wipe out the app's configuration directory at:

* `%APPDATA%\Opentrons` on Windows
* `~/.config/Opentrons` on Linux
* `~/Library/Application Support/Opentrons` on macOS

Grab a build from #builds and make sure everything works! We'll need tests on:

- [ ] Mac
- [ ] Linux
- [ ] Windows

### self-update testing

For self-update testing, we've got these builds that point at a testing bucket instead of our normal deploy bucket. The "stable" channel is set to `v0.0.0` and "beta" channel is set to `v0.0.0-beta.0`. Flip back and forth between beta and stable to test app update.

- Mac: https://s3.amazonaws.com/ot-test-bucket/app-test-builds/Opentrons-v0.0.0-mac-dev.zip
- Linux: https://s3.amazonaws.com/ot-test-bucket/app-test-builds/Opentrons-v0.0.0-linux-dev.AppImage
- Windows: https://s3.amazonaws.com/ot-test-bucket/app-test-builds/Opentrons-v0.0.0-win-dev.exe

### CODE REVIEW

**Comment by mcous** [comment]
Sanity checked so far on:

- macOS 10.13 (High Sierra)
- Windows 7

Still to test:

- Linux (any of 'em)
- Autoupdate to newer version
- Autoupdate to older version (here there be dragons)

**Comment by sfoster1** [comment]
OSX
[x] connect to usb and wifi
[x] test a couple http endpoints like lights and home
[x] upload and simulate protocol

[x]

**Comment by mcous** [comment]
Apologies for the force push again. merge conflicts with `yarn.lock` because of a recent yarn upgrade

**Comment by mcous** [comment]
App self-update tested and working on Windows 7

**Pull request merged**
