### PR TITLE
feat(app): Enable support for IPv4 wired robots by default

### LINKED ISSUE #990: Wifi Robots Not Appearing on Windows
## Expected Behavior:
- Robots available over wifi should appear in available robots list (robots sidebar)

## Observed Behavior: 
- Robots connected over wifi do not appear in available robots list.

## Steps To Recreate
reported by @Laura-Danielle:
1. Open run app on Windows (version >= 2018-03-06)
2. Note wifi robots are not visible in robots list (the sidebar)

### LINKED ISSUE #1964: Unable to Connect Over USB
## Expected Behavior:
- User able to connect to robot via Run App over USB

## Observed Behavior
- User unable to see or connect to a robot via Run App over USB

## Steps to Recreate
_Note we have not been able to recreate this internally_
1) Plug in robot over USB
2) Open run app
3) Observe that your robot does not appear in the Robots List sidebar

## Resources

### PR DESCRIPTION
**Pull request by mcous**
## overview

This PR enables "new" discovery to support the container changes in #1970 by default in the app. It also adds the changes made in #2072 to the top-level Makefile so that `make push-api` and `make term` from the repo-level will automatically work with whatever ethernet robot you have plugged in (whether its a new IPv4 or an old IPv6 one).

Presumably (based on extensive in-house testing and positive results with users who were experiencing issues) fixes #990 and fixes #1964. This is the last known app-side blocker for the `3.3.0` release.

## changelog

- feat(app): Enable support for IPv4 wired robots by default 

## review requests

The components of this PR have been tested pretty extensively over the past few weeks, but we should be sanity checking this. Testing goal is to get something to break. Please go nuts; we need this to be solid.

If you do test, please leave notes in your comment so we can trace back any checkbox changes.

### OSes to test:

- [x] macOS
- [ ] Ubuntu (or any Ubuntu/Debian based Linux)
    - [ ] 14.04 LTS
    - [ ] 16.04 LTS
    - [ ] 18.04 LTS
- [ ] Windows
    - [ ] Windows 10
    - [ ] Windows 7

### API software versions to test:

- [ ] Tag `v3.2.0`
- [x] Current `edge`

### Robot configurations to check out:

- [ ] Ethernet connected legacy IPv6 robot
- [x] Ethernet connected to IPv4 robot
- [ ] WiFi connected legacy IPv6 robots (WiFi is not IPv6, so _should be_ no actual change here)
- [x] WiFi connected IPv4 robots
- [ ] Virtual smoothie

### Success criteria

- [x] Robots show up with their actual name (e.g. "opentrons-bitter-wood", not "Opentrons USB")
- [x] HTTP endpoints (e.g. lights) work
- [x] RPC endpoints (e.g. tip-probe) work
- [x] If RPC socket is closed by the server, user is alerted that connection has been lost
    - Simulate by killing process on robot
- [x] If network connectivity goes down without socket closing, user is alerted
    - Simulate by disabling WiFi or pulling the USB cord

### CODE REVIEW

**Comment by mcous** [comment]
Know problem: app crashes if currently connected robot becomes unhealthy (and, thus, disappears from the list). Working on a fix now

**Comment by sfoster1** [comment]
Pass on 3.3 OSX with the sole issue of sometimes if the robot disconnects (either by unplugging the USB or by disconnecting my wifi) the robot disconnected modal won't pop up - the connected list clears but there's no modal. Upon reconnecting, I get the modal.

**Comment by Laura-Danielle** [comment]
Tested on Windows 10.

Connected successfully to legacy IPv6 + robots on IPv4. Something I found while testing:

I could not set advanced settings on the legacy robot (which should have advanced settings API logic according to SW version).

**Comment by IanLondon** [comment]
WIP review:

Tested on Ubuntu 16.04 (well, Linux Mint edition)

Only tested IPv4 (Sunset) b/c we're still working on getting an IPv6 set up -- both ethernet & wifi work for all the success criteria listed.

Virtual smoothie also OK for all success criteria.

---

Also, looks like there's a merge conflict RN

**Pull request merged**
