### PR TITLE
refactor(api): Add GEB tiprack definition to default containers

### PR DESCRIPTION
**Pull request by Laura-Danielle**
## overview

GEB tiprack needs to be added to default containers for customers who are not utilizing
split_definitions feature flag. Also, there was a typo in the docs about the GEB tiprack definition
name.

## changelog

- Add GEB tiprack definition into 'default-containers'
- Edit docs to reflect correct definition name

### CODE REVIEW

**Comment by umbhau** [comment]
@Laura-Danielle should we call this the opentrons-tiprack-300ul?

Assuming this is for the custom tipracks GEB manufactures for Opentrons, not the off-the-shelf GEB tipracks.

**Comment by Laura-Danielle** [comment]
@umbhau I am not opposed to changing the name. @btmorr @pantslakz @howisthisnamenottakenyet thoughts?

**Comment by howisthisnamenottakenyet** [comment]
Not opposed to more specific naming.

**Comment by btmorr** [comment]
`opentrons-tiprack-300ul` is fine. Either one works for me, let's just change the documentation to match whatever we decide on

**Comment by andySigler** [comment]
The more specific naming, in my opinion, the better. If the tip-rack has a part number, that should be either in the name, or specified some other way. It is 100% conceivable that we will have a rev2 or even totally different design of the `opentrons-tiprack-300ul`

**Comment by mcous** [comment]
@andySigler raises a really good point about labware revisions. I'm ok with this PR going in (especially to fix up OT2 docs weirdness) but we should discuss how new versions of a given definition are going to play out

**Comment by Laura-Danielle** [comment]
@mcous @andySigler I think that's definitely something to keep in mind moving forward. We should definitely have a discussion about how to handle revisions/model numbers and where they live.

**Comment by pantslakz** [comment]
happy we're ridding of GEB in place of Opentrons

**Pull request merged**
