### PR TITLE
docs(api): Add a way to build a PDF version of the docs

### PR DESCRIPTION
**Pull request by sfoster1**
You have to install a latex distribution so this is not a default target for
anything at all and is not really guaranteed to be cross-platform but here it is.

Here's an example of the built PDF:

[OpentronsAPI.pdf](https://github.com/Opentrons/opentrons/files/2783458/OpentronsAPI.pdf)

### CODE REVIEW

**Comment by Laura-Danielle** [comment]
My only concern is that this will not solve the problem (or potentially create more confusion) for the types of users requesting PDF versions of the API.

If we are going to have this in our documentation, we need to be extremely specific about how/where they can go about downloading latex to generate a PDF. Will probably also want to refer them to the support article about setting up your repository.

**Comment by sfoster1** [comment]
I absolutely don't expect users to do this. This is a first pass at adding it as an internal dev tool. At least in the future (and possibly for this PR) we should make sure latex is installed on travis (yuck, and why I didn't want to do this right now) and actually put this somewhere on the docs page for download.

**Comment by sfoster1** [comment]
The new commit
- Makes sure the PDF gets to the dist/_static folder so it should go to pages
-Adds a link in the sidebar to the pdf
- Slightly changes the html output and fixes some clearly intended but broken stuff up (like actually having a GH link)

To see what it looks like, download and unzip this and navigate to it in a browser with the uri file:///path/to/unzipped/index.html

[dist.zip](https://github.com/Opentrons/opentrons/files/2784581/dist.zip)

**Comment by sfoster1** [comment]
[dist.zip](https://github.com/Opentrons/opentrons/files/2788082/dist.zip)

This commit fixes the version being wrong in the pdf by loading it from package.json and prevents the labware images from floating. It also eliminates some whitespace by using a different documentclass. I'm not touching this anymore without a really good reason 😄

**Pull request merged**
