### PR TITLE
copy over PR feature-30-container-bugs, with app-3-0 base. + slot sharing must be explicit

### PR DESCRIPTION
**Pull request by IanLondon**
## Description:

Same as https://github.com/OpenTrons/opentrons/pull/258, but using `app-3-0` as a base.

Plus:

* Small documentation cleanup
#292

* Lowercase Pipette axis arg by default
#315

---

> Placing multiple containers in a slot must be explicitly written by user. This achieved through the kwarg `share=` on `containers.load()`

```
containers.load('96-flat', 'B2')
containers.load('trough-12row', 'B2', share=True)
```

> Placing two containers of same type into the same slot requires at least one of them have a unique name:

```
containers.load('96-flat', 'B3')
containers.load('96-flat', 'B3', 'other-plate', share=True)
```

### Breaking changes

New restrictions for shared slots (detailed above).

`Deck.containers` now returns a list, not a dict.

No more `robot.containers()`, instead use `robot.get_containers()`

Remove unused "private" method `_get_all_containers(robot):` from `api/opentrons/util/state.py`

---

Check List:

- [ ] Are there breaking changes in the API and how are they being communicated?
- [x] Update containers documentation (docs.opentrons.com) to reflect the change
- [x] Who is reviewing your code?

### CODE REVIEW

**Comment by astaff** [comment]
LGTM 👍

**Comment by IanLondon** [comment]
@astaff @mcous 

The `make docs` is passing now,

build is failing at `The command "make -C app -j 2 build test && make -C app package" exited with 2.` -- just like the base branch, `app-3-0`.

Good to merge into `app-3-0` now?

**Comment by mcous** [comment]
`app-3-0` should not be failing the build. Looks like #318 broke the build; my bad for not catching that in my review. @Kadee80 or @IanLondon can you fix the CSS lint errors introduced in `app/ui/components/UploadPanel.css`? I'm 👍 once that is done

**Comment by Kadee80** [comment]
@mcous on the lint error now

**Comment by Kadee80** [comment]
@mcous linting errors fixed, please review again

**Pull request merged**
