### PR TITLE
feat(app): add Jupyter Notebook button to robot's Advanced Settings

### LINKED ISSUE #6102: feat: display link to jupyter notebook in robot settings page
# Overview

The process by which we [direct users to get to Jupyter](https://support.opentrons.com/en/articles/1795367-running-the-robot-using-jupyter-notebook) is a little involved. Since our instructions already involve sending users to the app to retrieve the IP address of the robot, would it make more sense to put a link on the robots page to open Jupyter in the user's browser?

This has come up before internally (probably externally, too), but I couldn't find a ticket for it so here we are.

# Acceptance criteria

- [ ] Robot settings page includes a button that will open Jupyter notebook in the user's browser
- [ ] The link will use the "best" IP address available for the robot (e.g. use U2E if it is available)
- [ ] Clicking the link sends an analytics event

# Implementation details

- Robot page has a link to open the robot's Jupyter notebook in an external browser
- ~Link is clickable regardless of the health status of the API server and/or update server~
    - Note: current CSS for the disable logic in the `<Card>` component makes this difficult
- IP in link driven by same IP preference logic (wired over wireless, etc) as other connectivity logic
 
# Proposed design

I think the "Advanced Settings" card makes the most sense, but the link could go anywhere:

### PR DESCRIPTION
**Pull request by mcous**
# Overview

This PR adds a button to open an OT-2's Jupyter Notebook in a web browser to the "Robot Controls" card in the robot settings page.

Copy reads:

> **Jupyter Notebook**
> 
> Open the [Jupyter Notebook](https://jupyter.org/) running on this OT-2 in your web browser. (Experimental feature! See [documentation](https://docs.opentrons.com/v2/new_advanced_running.html#jupyter-notebook) for more details.)

Closes #6102

# Changelog

- feat(app): add Jupyter Notebook button to Robot Controls
    - Clicking the button will send a `jupyterOpen` analytics event

# Review requests

1. Open the Robot's page
2. Click the "Open" button next to "Open Jupyter Notebook"
3. Browser should open to Jupyter Notebook
    - Note: this will only work with a real robot / RPi that's serving Jupyter on port 48888

# Risk assessment

Low. Good unit test coverage

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
In the future, I think a "Learn more" link in the description would be good. (Currently, I don't think we have a great introductory documentation page for that link to point to, so it makes sense to me to leave the link out, for now.)

**Review by amitlissack — APPROVED** [review]
Code looks good. And so does the video!

**Comment by mcous** [comment]
Shuffling some stuff around based on UX and support feedback. Should be ready for review again later todau

**Review by IanLondon — APPROVED** [review]
thanks for the vid otherwise I wouldn't have found the button!

code looks good but I don't have a robot so can only do api dev server. With that, `http://localhost:48888/` isn't running jupyter. Obvs non-blocking and I guess api dev server doesn't run a jupyter server too so that's expected?

**Comment by mcous** [comment]
Copy + placement approval from Support + UX via 👍's in Slack

**Pull request merged**
