### PR TITLE
feat(robot-server): Mock up of access control models and router.

### LINKED ISSUE #5746: feat(robot-server): Create mock-up of access control API
# Overview

Create a router and models for a basic access control API. The intention is to get approval before implementing business logic.

# Acceptance criteria

Endpoints must provide functionally to:

- [ ] create a token
- [ ] view existing tokens
- [ ] delete a token
- [ ] see if robot is controlled and by whom
- [ ] take control of robot
- [ ] release control of robot

### PR DESCRIPTION
**Pull request by amitlissack**
## overview

Mock up of API to interact with access tokens and take control of a robot.

See : https://coda.io/d/Session-State-Management_dZ8yJSRoO6_/Access-Control_suRGF#_lu_TE for more details

These are the new API
```
# Token stuff #
# Get all the tokens present in the system
GET /access/tokens
# Create a token. This could potentially be renamed login if we want to support authentication
POST /access/tokens
# Delete a token
DELETE /access/tokens/{token}

# Control #
# Get info about who is in control of some scope of the robot 
GET /access/controls/{scope}
# Try to give a token control of some scope of the robot 
POST /access/controls/{scope}
# Forcibly take control of some scope of the robot 
PUT /access/controls/{scope}/{token}
# Release control of robot scope
DELETE /access/controls/{scope}/{token}
```

Example of usage for taking control of robot:
```
request:
POST /access/tokens
response:
{
    'data': {
       'attributes': {
           'token': 'abc_123'
        }
    }
}

request
POST /access/controls/robot
{
    'data': {
       'attributes': {
           'token': 'abc_123'
        }
    }
}
```

## risk assessment

Zero. 

closes #5746

### CODE REVIEW

**Comment by mcous** [comment]
What would be an example client flow for calling these endpoints in the given user flows?

**Comment by mcous** [comment]
I think I like the sound of this. I'm a little more used to flows where the scopes (controls) are properties of the token rather that another resource, though I'm certainly not opposed to separating them because it looks fairly flexible. Do you have any reasoning on splitting them up like this?

**Comment by amitlissack** [comment]
> I think I like the sound of this. I'm a little more used to flows where the scopes (controls) are properties of the token rather that another resource, though I'm certainly not opposed to separating them because it looks fairly flexible. Do you have any reasoning on splitting them up like this?

I considered both. Somehow I felt like it didn't quite make sense to me that a scope would be a prop of the token, but the other way around. Also, the path got really long the other way around.

I don't feel strongly about it. So would happy to change if you prefer it.

**Comment by amitlissack** [comment]
> I think I like the sound of this. I'm a little more used to flows where the scopes (controls) are properties of the token rather that another resource, though I'm certainly not opposed to separating them because it looks fairly flexible. Do you have any reasoning on splitting them up like this?

I considered both. Somehow I felt like it didn't quite make sense to me that a scope would be a prop of the token, but the other way around. Also, the path got really long the other way around.

I don't feel strongly about it. So would happy to change if you prefer it.

**Pull request merged**
