### PR TITLE
fix(protocol-designer): when adding new module only update mag steps …

### LINKED ISSUE #4823: PD Bug: Adding temp deck messes with magnet steps moduleId field
## overview

Adding a temp module messes up existing saved magnet steps

## steps to reproduce

- Enable modules setting
- Make a protocol with a magnetic module
- Add and save some MAGNET steps
- Add a temperature module
- BAM! The MAGNET steps have selected the new temperature module (see their `moduleId`)

## notes

This is probably related to `unsavedStepForms` reducer handling `ADD_MODULE` action, I think it's not differentiating btw module types and this behavior should only happen (for MAGNET step) when magnetic modules are added!

### PR DESCRIPTION
**Pull request by shlokamin**
## overview
This PR closes #4823 by checking to see if a new module is a mag mod before overwriting previous magnet step module ids.

## review requests
Code review (especially the tests)

Enable modules in PD setting
Make a protocol with a magnetic module
Add and save some MAGNET steps
Add a temperature module
- [ ] Correct module is displayed in the step timeline
- [ ] Correct module is displayed inside the magnetic step form
- [ ] Correct plate is displayed in the step timeline
- [ ] Correct plate is displayed inside the magnetic step form

### CODE REVIEW

**Comment by shlokamin** [comment]
Yikes, I'll look into this

**Comment by shlokamin** [comment]
@Kadee80 there was an issue with a helper function called `getNextDefaultTemperatureModuleId `. Basically it would always try to grab the last step's module id (if there was one). Before this worked because of the [bug that Jenny found](https://github.com/Opentrons/opentrons/issues/4823) since before we weren't properly updating the step's module id. 

So the scenario was as follows:

- User adds magnetic module
- User adds magnet steps
- User adds temperature module
- Magnet steps get updated with **temperature module id** (because before we were not checking that the new module being added is actually a temperature module)
- User adds temperature step
- Temperature step gets populated with the **last step's (incorrect) module id** (which in this case, happens to be a **temperature step**)

After I fixed the issue of ensuring that we only update magnetic module steps if the new module being added is a magnetic module:

- User adds magnetic module
- User adds magnet steps
- User adds temperature module
- Magnet steps get updated with **new magnetic module id**
- User adds temperature step
- Temperature step gets populated with the **last step's module id** (which in this case, happens to be a **magnetic step**)

Which is not correct... we only want to populate the temperature step with the last step's module id if the last step is a temp step. 

So I fixed the helper function to do that, so we _should_ be groovy now. But please double check!

**Comment by Kadee80** [comment]
@shlokamin 
The desired behavior is when creating a temperature step to auto-select the temperature module (or TC if there is now Temperature Module on the Deck) for the first temperature step dropdown. All subsequent temperature steps then select the previously selected temp compat module.

**Comment by shlokamin** [comment]
@Kadee80 ya I think we are on the same page. The issue before was here in `protocol-designer/src/steplist/formLevel/getNextDefaultModuleId/index.js` since it's this function that determines the temp step form's default selected module id :

```
 const nextDefaultModule: string | null =
    (lastModuleStep && lastModuleStep.moduleId) ||
    findKey(equippedModulesById, m => m.type === TEMPDECK) ||
    findKey(equippedModulesById, m => m.type === THERMOCYCLER)
```
When trying to figure out what the default next temp module id should be, the first thing we would grab was the last step's module id, but the last step might not be a temp step at all (the issue in this PR was that it was actually a mag step). So I think by checking to see if the last step is a temp step first, this issue should be avoided: 

```
const nextDefaultModule: string | null =
    (isLastStepTemp(lastModuleStep) && lastModuleStep.moduleId) ||
    findKey(equippedModulesById, m => m.type === TEMPDECK) ||
    findKey(equippedModulesById, m => m.type === THERMOCYCLER) ||
    null
```

If the last step isn't a temp step, it'll first try to get the moduleid of the temp mod on the deck (if any), then the TC. 

Does that make sense? Or am I accidentally making things worse?

**Pull request merged**
