### PR TITLE
Add option to stop homing when swapping mounts

### PR DESCRIPTION
**Pull request by RAbuQamar**
## overview

Adding new feature that allows for more rapid control between pipette mounts

## changelog
-Added boolean "swap_home" to move_to() and fasthome()
-Modified fastehome() in driver_3_0.py to accept swap_home. If swap_home is false, return self.position instead of self.home(axis=axis, disabled=disabled). If retract move fails, set swap_home to true (mount will home).

### CODE REVIEW

**Comment by RAbuQamar** [comment]
Makes sense! I've modified the safety_margin to be set to 0 when swap_home is false. Tested it out as well, as seen in attachment
[video.zip](https://github.com/Opentrons/opentrons/files/4187961/video.zip)

**Comment by sfoster1** [comment]
@RAbuQamar I'm a bit confused, I can't quite see where it's setting margin=0.

How about this:
- Remove the `swap_home` parameter, since we're letting `margin` do all the work
- Default `margin=0` in the function definition of `opentrons.hardware_control.API.retract`.

That way it won't interfere with the post-drop-tip fast home call.

**Comment by RAbuQamar** [comment]
Ah, you see the reason you don't see it is because I forgot to push the commit to the right repo...
Sorry about that!

It's tossed in. I held on to the swap_home as that's the main parameter I use to stop fasthome from returning home:

# then home once we're closer to the endstop(s)
disabled = ''.join([ax for ax in AXES if ax not in axis.upper()])
if not swap_home:
    return self.position
return self.home(axis=axis, disabled=disabled)

I added this before the move:

if not swap_home:
    safety_margin = 0
# move some mm distance away from the target axes endstop switch(es)
    destination = {
        ax: self.homed_position.get(ax) - abs(safety_margin)
        for ax in axis.upper()
    }

**Comment by sfoster1** [comment]
> Ah, you see the reason you don't see it is because I forgot to push the commit to the right repo...
> Sorry about that!
> 
> It's tossed in. I held on to the swap_home as that's the main parameter I use to stop fasthome from returning home:
> 
> ```
> # then home once we're closer to the endstop(s)
> disabled = ''.join([ax for ax in AXES if ax not in axis.upper()])
> if not swap_home:
>     return self.position
> return self.home(axis=axis, disabled=disabled)
> ```
> 
> I added this before the move:
> 
> ```
> if not swap_home:
>     safety_margin = 0
> # move some mm distance away from the target axes endstop switch(es)
>     destination = {
>         ax: self.homed_position.get(ax) - abs(safety_margin)
>         for ax in axis.upper()
>     }
> ```

Right, my argument is basically that instead of not returning home we simply set the margin to 0 and gain some of that speed. That's a lot easier to be sure works in every weird circumstance from odd protocols and geometries.

**Comment by RAbuQamar** [comment]
Ah, that may be good for other customers, but for our specific purposes that wouldn't work. The homing itself added an additional minute to a full move, and left liquid our well dry for too long.
Our manual processes have scientists having the aspiration tip and the dispensing tip both down at the same time, simultaneously dispensing and aspirating as to keep the well wet even when swapping solution.

I'd actually try to only retract to the move geometry clearance height, I wouldn't want to home at all when continuing movement on the same labware.

I can toss in the edit you'd requested for the pull request, but I'll probably continue to use the swap_home for our specific purposes

**Comment by sfoster1** [comment]
> Ah, that may be good for other customers, but for our specific purposes that wouldn't work. The homing itself added an additional minute to a full move, and left liquid our well dry for too long.
> Our manual processes have scientists having the aspiration tip and the dispensing tip both down at the same time, simultaneously dispensing and aspirating as to keep the well wet even when swapping solution.
> 
> I'd actually try to only retract to the move geometry clearance height, I wouldn't want to home at all when continuing movement on the same labware.
> 
> I can toss in the edit you'd requested for the pull request, but I'll probably continue to use the swap_home for our specific purposes

Yeah, that makes sense to me. I think we can't merge the full swap_home thing upstream, but I'm happy to take the margin change.

PS sorry for taking so long with this comment - had to do a bunch of release QA.

**Comment by RAbuQamar** [comment]
No worries on the delay, totally understandable.

I'll keep this PR open as I have a mod that I'm hoping to work on for this. My idea is to make the retraction only go up to a labware's safety height if the pipettes are moving to another well within the same labware.
This'll speed things up for us and may be useful to you guys

**Comment by RAbuQamar** [comment]
Apologizes for the abrupt close!

I noticed you guys have moved to 3.16 that has major changes to the hardware's init.py that was the main change in this commit.
I've synced my fork to your changes but needed to drop my mods to do so. I'll revisit this function after I've navigated through the new api.
When I do, I'll try executing the idea I had shared above!

**Pull request closed without merging**
