### PR TITLE
(Chore) Switch out ESLint for standard

### PR DESCRIPTION
**Pull request by mcous**
After discussion with @opentrons/js, we've decided to switch our linter to [`standard`](https://standardjs.com/) to:

* Remove maintenance costs related to a lint configuration
* Remove style decisions from our hands to speed up reviews and reduce bikeshedding
* Have a generally good lint configuration that is strict enough to catch a bunch of errors but flexible enough to allow expressive code

This PR also continues an ongoing task of consolidating build tasks in the `Makefile` rather than splitting them arbitrarily between `package.json` scripts and the `Makefile` (`make` was preferred over `npm` because we're using `make` on the Python side and one build tool is better than two). To run linting:

``` shell
cd app

# run linting
make lint

# run linting with auto-fixing where possible
make lint-fix
```

Once this PR is approved, I'm going to run lint-fix as and push another commit because the diff is gonna be onerous...

### CODE REVIEW

**Comment by mcous** [comment]
Text editor plugins: https://standardjs.com/index.html#are-there-text-editor-plugins

**Comment by IanLondon** [comment]
Awesome! I checked for eslint remnants, and found there's...

1) `./app/test/.eslintrc` which looks like a good thing to lint the tests and make sure you don't pass linting with disabled/`.only` tests. I believe this will still work as-is under `standard` (right?)

2) A bunch of eslint logo images... dunno what they are for
./app/internals/img/eslint-padded-90.png
./app/internals/img/eslint.png
./app/internals/img/eslint-padded.png

**Comment by mcous** [comment]
> ./app/test/.eslintrc which looks like a good thing to lint the tests and make sure you don't pass linting with disabled/.only tests. I believe this will still work as-is under standard (right?)

I'm pretty sure this won't work with standard. Ideally we catch this in code review. Alternatively, we use [`standardx`](https://github.com/standard/standardx), which is relatively new.

> A bunch of eslint logo images... dunno what they are for

What are any of these images for? Why are they here? I'd like to remove them all. @astaff do you know?

**Comment by mcous** [comment]
Leaving lint fixes for a little later to avoid merge conflicts while everything is still high churn

**Comment by astaff** [comment]
@mcous @IanLondon yes, weird icons is a residue from porting over https://github.com/chentsulin/electron-react-boilerplate . thanks for cleaning it up 👍

**Pull request merged**
